### PR TITLE
Initial implementation of SNI.

### PR DESCRIPTION
**Pull request by tolysz**
Keter is created for hosting multiple apps; but all certificates need to be bundled together as one.
This patch adds possibility to have a different certificate per webapp... extending other stanzas should be as easy as that one.
PR is complete, however if someone have time to extend it to other parts (i.e. not just webapps)
And allow loading certificates require absolute paths (I placed various todos so feel free to pick them up).

### CODE REVIEW

**Comment by creichert** [comment]
Looks good to me. I'm not deeply familiar w/ some parts of the code, how does this interact w/ ssl configurations specified in the global keter config?

Either way, great stuff

**Comment by tolysz** [comment]
;)
SNI certs <> Global ssl 
Once relative paths are sorted you could deploy certificates with bundles. 
Either way it is a step towards letsencrypt.org.

**Comment by creichert** [comment]
I've reviewed this to the best of my ability. Ideally we have more tests in the future. Also, while the `foo_10` is a good place for the "full" config docs, it would be ideal to move into the README since that's where most people look initially.

Thanks!

**Comment by tolysz** [comment]
Thanks,
This should work good enough; better than the current state anyway :)

**Pull request merged**
