### PR TITLE
Add ability to rewrite incoming URLs

### PR DESCRIPTION
**Pull request by vlatkoB**
Current Rewrite module allows rewriting only headers. This PR adds ability to rewrite the URLs as well.

The following syntax is added to keter.yaml:
```yaml
    rewrite-path:
       - match-type: host-path-query
         if-matches: ^//(.*)-subdomain.host.com(/?)\\?query=(.*)
         rewrite-to: //subdomain.host.com/abc?query=$3&part=$1
```
Matching is based on "first-match-wins", so ordering is important.

There are 4 different matching types that define which part of URL is received for matching, and what can actually be rewritten:

1. path-only
  - Receives only path for matching
  - Only path is rewritten
  - Example:    
       ```/bar/baz```   >>   ```/baz/bar```

2. path-query
  - Receives path and query for matching
  - Path and query are rewritten
  - Example:  
      ``` /bar/baz/?query=Today```   >> ``` /baz/bar/?today=Query```

3. host-path
  - Receives host and path for matching
  - Only path is rewritten (for now)
     - Host is taken from "reversed-host" (for now)
  - New query is merged with Old query.
  - New query takes precedence, if equal exists in both.
  - Queries are reordered alphabetically.
  - Example:
      ``` //sub-dom.foo.com/bar/baz```   >>   ``` //sub-dom.foo.com/baz/bar?a=sub-dom```

4 . host-path-qs
  - Receives host, path and query for matching
  - Path and query string are rewritten
    - Host is taken from "reversed-host"
  - New query is merged with Old query.
  - New query takes precedence, if equal exists in both.
  - Queries are reordered alphabetically.
  - Example:  
        ``` //sub-dom.foo.com/bar/baz?a=1&b=2&c ```
                >> ``` //sub-dom.foo.com/baz/bar?a=sub-dom&b=1&c=```

To solve:
  1. In `mkRequest`, `redirectCount` is set to `0`. Do not know why. Need it to be larger than 0.
  2. Currently, for sub-domain rewriting one must specify stanza for each sub-domain. (code for host/subdomain rewriting is removed from this PR).

(Sorry for the cabal mess, emacs automatically orders entries.)

Let me know what you think.

vlatko

### CODE REVIEW

**Comment by creichert** [comment]
@vlatkoB Very cool! Thanks for the PR. I'll give a bit more time for anyone else raise any issues before merging.

Would you mind adding an example here: https://github.com/snoyberg/keter/blob/master/incoming/foo1_0/config/keter.yaml#L1

Thanks for the tests and documentation as well.

**Comment by vlatkoB** [comment]
@creichert Have you written the Rewrite.hs module?

**Comment by creichert** [comment]
@vlatkoB I did not write the Rewrite module

**Comment by vlatkoB** [comment]
@creichert I had to increase the redirectCount in mkRequest, but do not know why did original author set it to 0.

**Comment by tolysz** [comment]
`redirectCount = 0` is when redirects are disabled; maybe this was the assumption when reversing the app?

**Comment by vlatkoB** [comment]
I was wondering what effect enabling redirects can have. Maybe original author can comment?

**Comment by vlatkoB** [comment]
@creichert I also think the merge should wait some time. After New Year people might test more and comment. There are some more stuff I wanted to do, but it'll wait. :-)

**Comment by creichert** [comment]
@vlatkoB Sounds good, I can wait. Overall, the commit looks good minus the small bits. I'd be interested to hear thoughts on the redirect count as well. Otherwise, I'm excited about this feature. Thanks!

**Comment by creichert** [comment]
@vlatkoB Any updates on this PR? I'm happy to help push things in the right direction if needed.

**Comment by vlatkoB** [comment]
@creichert Sorry for delayed answer. We actually abandoned it because for https connections it doesn't always work as expected, i.e correctly. I suspect it is about `redirectCount`, but had no time to debug nor test it properly.

We solved our problem by giving up redirects and moving most of it (not host rewrites) under webapp stanza in keter. So it is not about redirects anymore, but internal url rewrites (i.e. user doesn't see the url change in address bar). This is in production for a few months now.
If you think that (rewrites, not redirects) might be of interest to make a PR, let me know.

This PR should be closed, unless someone wants to take over.

**Comment by creichert** [comment]
@vlatkoB No worries, thanks for the detail. Good to know. I'll close this for now but feel free to re-open if there are future revelations. Thanks!

**Pull request closed without merging**
