### PR TITLE
Create a copy of the install script that only sets up files needed by keter

### PR DESCRIPTION
**Pull request by rasheedja**
I created this script so I can easily create all the files needed by keter onto a server that I had transferred
a keter binary to. It's up to you if you want to include it in the main repo.

### CODE REVIEW

**Comment by creichert** [comment]
I like this. Is there any way that the install script can use this instead of copying the code?

**Comment by rasheedja** [comment]
@creichert I've made a commit that calls the new script from within the install script. It should work without any problems but I'll try to test it this weekend just to make sure.

**Comment by creichert** [comment]
@rasheedja Perfect, thank you. I'm working on fixing CI and possibly providing a docker container which will use your script so I'll have a chance to test it as well. Thanks!

**Comment by rasheedja** [comment]
I've realized that this won't work for people who run the script through
wget. I think a better idea would be to use a bash parameter which
determines whether or not the install is skipped so that the whole process
is still in one file. I'll look into it tomorrow

**Comment by rasheedja** [comment]
@creichert I've opened #186 which is the same script but with an optional bash option to skip the install.

**Pull request closed without merging**
