### PR TITLE
Remote postgres

### PR DESCRIPTION
**Pull request by bermanjosh**
#100 

Keter can manage a remote DB server, based on app settings. I believe it should be backwards compatible with existing postgres.yaml files, so I think only a minor version bump is necessary. 

This doesn't deal with the issue @ygale raised; it actually compounds the issue, as now there are more assumptions about postgres's setup. There are a few issues which might need to be decided before this is merged:
* The assumptions regarding how the remote DB server has been setup; specifically, the `trust` method note. Is it worth taking the time to try to allow for a username / password to be set in the app's settings? As a general rule, I don't like requiring plain-text passwords. 
* As I noted in the readme, if an app is changed to use a different server, but said app already exists in the postgres.yaml, keter will prioritize the old settings and ignore the new. (This is related to another issue which I've been thinking about - allowing for the postgres.yaml info to be updated without restarting keter).

### CODE REVIEW

**Comment by creichert** [comment]
Thanks! I'll have time to review and test this a little later today.

I do agree with @ygale but I don't believe this patch really has a huge
impact since we already rely on the `psql` executable.  Also, the
suggested alternative is significantly more work than this patch.

**Comment by ygale** [comment]
@creichert Actually,  it *is* a huge impact. It negates the whole purpose of the feature, which is not to require having PostgeSQL installed on the same server as keter. And no, the alternative is not significantly more work. It's a few simple lines of code, plus what @bermanjosh did. We already have a working version in production and would be happy to share.

The issue is that it creates a dependency on `postgresql-simple`. So it's mainly a package maintainer question: do we create the dependency, or do we create a cabal flag, or do we split `keter ` into separate packages...?

**Comment by snoyberg** [comment]
I'm stumped. How does this add a dependency on PostgreSQL on the server? Seems like it depends on the psql binary, which is the PostgreSQL client, which would need to be installed anyway in order to use postgresql-simple.

**Comment by creichert** [comment]
The `psql` binary doesn't impose a dependency on
`postgresql-server`. It's installed from `postgresql-client-common`
which only requires the `netbase` package. Keter already requires anyone
using the postgres plugin to have `psql` installed.

@ygale The purpose of this feature is not to prevent having postgresql
installed. It's to enable an app to connect to postgresql on another
host.

This patch will have no effect on current Keter users and imposes no
extra dependencies. I am not opposed to more advanced postgresql
features but splitting that into another package will definitely require
maintenance.

**Comment by ygale** [comment]
@snoyberg postgresql-simple does not depend on the client binaries or a server. It only requires libpq. Current keter requires that and more if you want to use it with PostgreSQL.

I thought I saw that psql requires a server installation on redhat, but I now see that I was wrong, sorry. It does require additional system packages beyond libpq though.

The fact that keter works by shelling out to sudo psql rather than using libpq directly is a hack that we need to get rid of. We can't use keter out of the box for a current enterprise client even though we can sudo root, because the ACL settings we were given prevent keter from shelling out to sudo root.

The current keter already has hidden dependencies on at least the postgesql binaries and libpq if you want to use it with PostgreSQL, and it also requires extreme privilege escalation that is potentially unsafe. If we switch to using libpq directly - which at least from the security point of view is the only correct way to access PostgreSQL programmatically - then keter will only need enough privilege to bind to whatever listener ports are configured.

@creichert I completely understand your reservations about the additional maintenance burden if we split off another package. Another option is a `+libpq` cabal flag - can we add that? We can even leave in the current shell-out hack for PostgreSQL support when the flag is not enabled, which would be the default.

@bermanjosh Your patch might be useful for someone, but we ourselves wouldn't be able to use it due to the sudo problem. You could add additional logic and configuration to control whether keter tries to use sudo - it isn't needed when you are accessing a remote server - but in my opinion that is just adding a hack on top of a hack. It would be the same amount of work to provide a libpq option instead, and we already have code for that.

**Comment by bermanjosh** [comment]
@ygale 
Ok, putting aside the more fundamental question of psql vs. libpq, you're right in that there's no purpose in a sudo cmd when accessing a remote host's DB, so I'll change that.

**Comment by creichert** [comment]
@bermanjosh Can you add an example of the new configuration options here: https://github.com/snoyberg/keter/blob/master/incoming/foo1_0/config/keter.yaml#L68

@ygale I would definitely be in favor of the libpq flag. To be clear, you are talking about using `postgresql-simple` or `postgresql-libpq`, right? Is this something you want to tackle?

**Comment by bermanjosh** [comment]
@creichert Right - good call. Taken care of. Anything else you can think of?
Thanks

**Comment by ygale** [comment]
@creichert Yes we have a local version of keter that does that already, with postgresql-simple. We just need to merge it with the work in this current PR (nice work @bermanjosh !). I or @bermanjosh, one of us, will put together another PR after this one is merged.

To make it absolutely clear:

1. The flag will be false by default.
2. When the flag is false, there is no additional package dependency. Everything as before.
3. Behavior when the flag is false: keter works exactly the way it does after this first PR. I.e., with no remote server configuration, exactly as before. And with remote server configuration, shell out to psql without sudo.
4. When the flag is true, add a dependency on `postgresql-simple`, and use `postgresql-simple` to send keter's `CREATE` queries to Postgresql instead of shelling out to psql.

Sound OK?

**Comment by creichert** [comment]
@ygale Sounds perfect. I think that will be a good first step to
actually supporting _more_ plugin features and eventually splitting off
the package if we need to. Thanks.

@joshberman no, everything looks good I just wanted an example to do
some final testing against.


Eventually, we'll be able to make some improvements to the test-suite.

**Comment by creichert** [comment]
Thanks!

**Pull request merged**
