### PR TITLE
Bump version to 1.4.2.1.

### PR DESCRIPTION
**Pull request by creichert**
* Update changelog with default connection time bound fix.

### CODE REVIEW

**Comment by snoyberg** [comment]
I think it would make sense for me to give you Hackage upload rights. Are you OK with that? If so, what's your Hackage username?

**Comment by snoyberg** [comment]
And by the way, you've been doing an awesome job of maintaining keter, well done, and much appreciated!

**Comment by creichert** [comment]
@snoyberg Thanks, I appreciate that. I'll be happy to have upload rights. It's ChristopherReichert (http://hackage.haskell.org/user/ChristopherReichert)

**Comment by snoyberg** [comment]
Cool, added.

**Pull request merged**
