### PR TITLE
Add new CPP for fields introduced in process 1.3 and 1.4

### PR DESCRIPTION
**Pull request by tolysz**
A stab at fixing https://github.com/snoyberg/keter/issues/147
I am not sure about `new_session = True`  but otherwise works with the latest `lts` and `nightly`

### CODE REVIEW

**Comment by tolysz** [comment]
Looks like `http-reverse-proxy-0.4.3` can not compile anymore... via cabal.

**Comment by creichert** [comment]
LGTM, thanks!

**Comment by creichert** [comment]
@tolysz Any idea why this only failed on merge? https://travis-ci.org/snoyberg/keter/builds/152831584

**Comment by tolysz** [comment]
https://github.com/yesodweb/wai/issues/577
It is so good to have `travis` use `cabal` :) we can peek into `--revision head` of `stack` :)

Maybe we should have `lts` and `nightly` targets as well? This way we could see if it would build with `stack`?

**Pull request merged**
