### PR TITLE
Add filesystem-path compatibility for older fsnotify versions.

### PR DESCRIPTION
**Pull request by creichert**
@snoyberg I tested against lts-2.1. lts-2.2 still has issues with http-reverse-proxy.

### CODE REVIEW

**Comment by snoyberg** [comment]
This is fine as-is. The one downside is that it introduces a spurious dependency on system-filepath when using fsnotify >= 0.2. You can work around this with a flag in the cabal file, but this can cause problems with the cabal dependency solver in older versions... in other words, LGTM, merge when you're ready :)

**Comment by creichert** [comment]
Ok, thanks. I'll at least add some `stack build --dry-run` to the Travis CI scripts for now too.

**Comment by creichert** [comment]
I don't mind adding the flag, actually, if the older cabal versions aren't a bigger issue than the spurious dependency.

**Comment by snoyberg** [comment]
Your call, I'm fine either way. Here's what it would look like:

```diff
+flag system-filepath
+  description: Use system-filepath
+  default: False
+
 Library
   Build-depends:       base                      >= 4             && < 5
                      , directory
@@ -34,7 +38,6 @@ Library
                      , blaze-builder             >= 0.3           && < 0.5
                      , yaml                      >= 0.8.4         && < 0.9
                      , unix-compat               >= 0.3           && < 0.5
-                     , fsnotify                  >= 0.2.0.2
                      , conduit                   >= 1.1
                      , conduit-extra             >= 1.1
                      , http-reverse-proxy        >= 0.4.2         && < 0.5
@@ -61,6 +64,14 @@ Library
   if impl(ghc < 7.6)
     build-depends:
                     ghc-prim
+
+  if flag(system-filepath)
+    build-depends:     fsnotify >= 0.1 && < 0.2
+                     , system-filepath
+    cpp-options:       -DSYSTEM_FILEPATH
+  else
+    build-depends:     fsnotify >= 0.2.0.2
```

**Comment by creichert** [comment]
Ok, this looks good. I'm merging, pushing to hackage, and have a fix coming up for stackage. Thanks!

**Pull request merged**
